### PR TITLE
change ordering to abstain nay yay + format

### PR DESCRIPTION
**Pull request by saiakilesh**

### CODE REVIEW

**Comment by 0xDigitalOil** [comment]
Hey @saiakilesh why change interface and struct order instead of keeping the order and feeding the vote tallies in inverse order?

**Comment by saiakilesh** [comment]
> Hey @saiakilesh why change interface and struct order instead of keeping the order and feeding the vote tallies in inverse order?

I think it is better for code readability. 

Having the 2,1,0 order seems messy.

**Comment by 0xDigitalOil** [comment]
Not strongly against or anything, but I think it's cleaner to not touch the interface (although not a big deal to adjust on my end as well), plus cleaner to transfer data in the same order that it's shown, sent and indexed (0, 1, 2) on Nouns: for, against, abstain.

wdyt?

**Comment by saiakilesh** [comment]
> Not strongly against or anything, but I think it's cleaner to not touch the interface (although not a big deal to adjust on my end as well), plus cleaner to transfer data in the same order that it's shown, sent and indexed (0, 1, 2) on Nouns: for, against, abstain.
> 
> wdyt?

Ok, let's do it like that. Will make the changes.

**Comment by dtebbs** [comment]
Yeah, probably worth keeping the interface order as yes, no, abstain.  To address the point about the strange order (2,1,0) in the assignment, let's include a comment in the code to explain.

**Review by 0xDigitalOil — APPROVED** [review]
Good!

**Pull request merged**
